name: CodeClimate Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codeclimate:
    name: Run CodeClimate Analysis
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup .NET Environment
      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x'

      # 3. Restore dependencies
      - name: Restore dependencies
        run: dotnet restore

      # 4. Build project
      - name: Build project
        run: dotnet build --no-restore

      # 5. Run tests and generate coverage report
      - name: Run tests and generate coverage
        run: |
          dotnet test --collect:"XPlat Code Coverage" --no-build
          mv **/coverage.cobertura.xml coverage.cobertura.xml || echo "Coverage file not found"

      # 6. Upload coverage to CodeClimate via Docker
      - name: Upload Coverage Report to CodeClimate
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          echo "Uploading coverage report to CodeClimate..."
          docker run --rm \
            -v $(pwd):/code \
            -e CC_TEST_REPORTER_ID=${CC_TEST_REPORTER_ID} \
            codeclimate/test-reporter:latest \
            after-build --input coverage.cobertura.xml
