name: CodeClimate Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codeclimate:
    name: Run CodeClimate Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CodeClimate CLI
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > codeclimate-test-reporter
          chmod +x codeclimate-test-reporter
          sudo mv codeclimate-test-reporter /usr/local/bin

      - name: Run CodeClimate Test Coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          codeclimate-test-reporter before-build
          # Thay lệnh bên dưới bằng lệnh test phù hợp với dự án của bạn
          npm test -- --coverage || php vendor/bin/phpunit --coverage-text
          codeclimate-test-reporter after-build --exit-code $?
