name: CodeClimate Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  codeclimate:
    name: Run CodeClimate Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install CodeClimate CLI
        run: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > codeclimate-test-reporter
          chmod +x codeclimate-test-reporter
          sudo mv codeclimate-test-reporter /usr/local/bin

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0.x' # Chọn phiên bản phù hợp với dự án của bạn

      - name: Restore dependencies
        run: dotnet restore

      - name: Build project
        run: dotnet build --no-restore

      - name: Run tests and generate coverage
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        run: |
          codeclimate-test-reporter before-build
          dotnet test --collect:"XPlat Code Coverage" --no-build
          reportgenerator -reports:**/coverage.cobertura.xml -targetdir:coverage
          codeclimate-test-reporter after-build --exit-code $?
