name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  build-and-analyze:
    name: Build & Analyze with SonarCloud
    runs-on: windows-latest  # Chạy trên Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Cài đặt MSBuild từ Visual Studio
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      # Khôi phục dependencies
      - name: Restore dependencies
        run: |
          msbuild SHOP.sln /t:Restore

      # Build project
      - name: Build project
        run: |
          msbuild SHOP.sln /p:Configuration=Release

      # Upload artifacts (nếu cần)
      - name: Upload build artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-artifacts
          path: "**/bin/Release/"

      # Phân tích với SonarCloud
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=toanthang204_QL-SHOP
            -Dsonar.organization=toanthang204
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*.dll
            -Dsonar.verbose=true
