name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  build-analyze:
    name: Build & Analyze with SonarCloud
    runs-on: ubuntu-latest  # Chạy trên Linux

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '4.7.2'

      - name: Restore dependencies
        run: dotnet restore SHOP.sln

      - name: Build project
        run: dotnet build SHOP.sln --configuration Release

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=toanthang204_QL-SHOP
            -Dsonar.organization=toanthang204
            -Dsonar.sources=.
            -Dsonar.exclusions=**/*.dll
            -Dsonar.verbose=true
