name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read # Cho phép SonarCloud phân tích và chú thích vào PR

jobs:
  Analysis:
    runs-on: windows-latest # Chạy trên Windows vì dự án dùng .NET Framework

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Cài đặt MSBuild và môi trường .NET
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      # 3. Restore dependencies
      - name: Restore dependencies
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" /t:Restore SHOP.sln

      # 4. Build project
      - name: Build project
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\MSBuild\Current\Bin\msbuild.exe" /p:Configuration=Release SHOP.sln

      # 5. Chạy Unit Test nếu có
      - name: Run tests
        run: |
          & "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\IDE\Extensions\TestPlatform\vstest.console.exe" SHOP\YourTestProject.dll

      # 6. Phân tích với SonarCloud
      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }} # Token đã tạo trên SonarCloud
        with:
          args: >
            -Dsonar.projectKey=toanthang204_QL-SHOP
            -Dsonar.organization=toanthang204
            -Dsonar.verbose=true
