name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  build-and-analyze:
    name: Build & Analyze with SonarCloud
    runs-on: windows-latest  # Chạy trên Windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup MSBuild cho .NET Framework
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      # Cài đặt Java (SonarScanner yêu cầu Java)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      # Download và cài đặt SonarScanner CLI
      - name: Install SonarScanner CLI
        run: |
          choco install sonarscanner

      # Restore dependencies
      - name: Restore dependencies
        run: |
          msbuild SHOP.sln /t:Restore

      # Build project
      - name: Build project
        run: |
          msbuild SHOP.sln /p:Configuration=Release

      # Chạy SonarScanner để phân tích mã nguồn
      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          SonarScanner.MSBuild.exe begin /k:"toanthang204_QL-SHOP" /o:"toanthang204" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          msbuild SHOP.sln /p:Configuration=Release
          SonarScanner.MSBuild.exe end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
