name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  build-and-analyze:
    name: Build & Analyze with SonarCloud
    runs-on: windows-latest

    steps:
      # 1. Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Setup MSBuild
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      # 3. Setup Java (required for SonarScanner)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      # 4. Download and Install SonarScanner for MSBuild
      - name: Install SonarScanner for MSBuild
        run: |
          Invoke-WebRequest -Uri "https://binaries.sonarsource.com/Distribution/sonar-scanner-msbuild/sonar-scanner-msbuild-5.13.0.66777-net46.zip" -OutFile "sonar-scanner-msbuild.zip"
          Expand-Archive sonar-scanner-msbuild.zip -DestinationPath C:\sonar-scanner
          echo "C:\sonar-scanner\sonar-scanner-msbuild-5.13.0.66777-net46" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      # 5. Restore dependencies
      - name: Restore dependencies
        run: |
          msbuild SHOP.sln /t:Restore

      # 6. Build the project
      - name: Build project
        run: |
          msbuild SHOP.sln /p:Configuration=Release

      # 7. Run SonarScanner analysis
      - name: Run SonarScanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          C:\sonar-scanner\sonar-scanner-msbuild-5.13.0.66777-net46\SonarScanner.MSBuild.exe begin /k:"toanthang204_QL-SHOP" /o:"toanthang204" /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
          msbuild SHOP.sln /p:Configuration=Release
          C:\sonar-scanner\sonar-scanner-msbuild-5.13.0.66777-net46\SonarScanner.MSBuild.exe end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
