name: SonarCloud analysis

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  pull-requests: read

jobs:
  Analysis:
    runs-on: windows-latest  # Sử dụng Windows runner vì .NET Framework không chạy trên Ubuntu

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Không cần cài .NET Framework 4.7.2 vì Windows runner đã có sẵn
      - name: Restore dependencies
        run: msbuild /t:Restore SHOP.sln

      - name: Build project
        run: msbuild /p:Configuration=Release SHOP.sln

      - name: Run tests
        run: |
          vstest.console.exe SHOP/YourTestProject.dll

      - name: Analyze with SonarCloud
        uses: SonarSource/sonarcloud-github-action@v2.2.0
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=YourProjectKey
            -Dsonar.organization=YourOrganizationKey
